const express =require('express')
const app=express()
const port=4050
const dbConnection=require('./db')
app.use(express.json())
app.use('/api/cars/' ,require('./routes/carsRoute'))
app.use('/api/users/' ,require('./routes/usersRoute'))
app.get('/',(req,res)=>res.send('hello world'))
app.listen(port,()=>console.log(`Node Js server started in port ${port}`))
app.use('/api/bookings/' ,require('./routes/bookingsRoute'))